modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/celestomm/Dynamic-Music/issues"
license = "LGPLv3"

[[mods]]
modId = "dynmus"
version = "${version}"
displayName = "Dynamic Music"
authors = "LudoCrypt, celeri"
description = "Adds more dynamic music ques, and more music itself for that!"
logoFile = "icon.png"
displayTest = "IGNORE_ALL_VERSION"

[[dependencies.dynmus]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.dynmus]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dynmus]]
modId = "architectury"
mandatory = true
versionRange = "[4.10.88,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.dynmus]]
modId = "cloth_config"
mandatory = true
versionRange = "[6.3.81,)"
ordering = "AFTER"
side = "CLIENT"