modLoader = "javafml"
loaderVersion = "[37,)"
issueTrackerURL = "https://github.com/celestomm/Dynamic-Music/issues"
license = "LGPLv3"

[[mods]]
modId = "dynmus"
version = "${version}"
displayName = "Dynamic Music"
authors = "LudoCrypt, celeri"
description = "Adds more dynamic music ques, and more music itself for that!"
logoFile = "icon.png"
displayTest = "IGNORE_ALL_VERSION"

[[dependencies.dynmus]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.dynmus]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dynmus]]
modId = "architectury"
mandatory = true
versionRange = "[2.10.12,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.dynmus]]
modId = "cloth_config"
mandatory = true
versionRange = "[5.3.63,)"
ordering = "AFTER"
side = "CLIENT"